// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class AdContentValue
    {
        public long AdContentValueId { get; set; }
        public long AdContentId { get; set; }
        public string ContentValue { get; set; }

        public virtual AdContent AdContent { get; set; }
    }
}