// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class AdContent
    {
        public AdContent()
        {
            AdContentValues = new HashSet<AdContentValue>();
        }

        public long AdContentId { get; set; }
        public long ClassifiedAdId { get; set; }
        public int AdTemplateConfigId { get; set; }

        public virtual AdTemplateConfig AdTemplateConfig { get; set; }
        public virtual ClassifiedAd ClassifiedAd { get; set; }
        public virtual ICollection<AdContentValue> AdContentValues { get; set; }
    }
}