// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vision.Models
{
    [Table("AdTemplateOption")]
    public partial class AdTemplateOption
    {
        [Key]
        public int AdTemplateOptionId { get; set; }
        public int ParentId { get; set; }
        public int AdTemplateConfigId { get; set; }
        [StringLength(150)]
        public string OptionAr { get; set; }
        [StringLength(150)]
        public string OptionEn { get; set; }
        public string Pic { get; set; }
        public int SortOrder { get; set; }

        [ForeignKey("AdTemplateConfigId")]
        [InverseProperty("AdTemplateOptions")]
        public virtual AdTemplateConfig AdTemplateConfig { get; set; }
    }
}