// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vision.Models
{
    [Table("AdTemplateConfig")]
    public partial class AdTemplateConfig
    {
        public AdTemplateConfig()
        {
            AdContents = new HashSet<AdContent>();
            AdTemplateOptions = new HashSet<AdTemplateOption>();
        }

        [Key]
        public int AdTemplateConfigId { get; set; }
        public int FieldTypeId { get; set; }
        [StringLength(200)]
        public string AdTemplateFieldCaptionAr { get; set; }
        [StringLength(200)]
        public string AdTemplateFieldCaptionEn { get; set; }
        public int ClassifiedAdsCategoryId { get; set; }
        public int SortOrder { get; set; }
        public bool IsRequired { get; set; }
        public bool HasChild { get; set; }
        public int ParentId { get; set; }
        public int Step { get; set; }
        public string ValidationMessageAr { get; set; }
        public string ValidationMessageEn { get; set; }

        [ForeignKey("ClassifiedAdsCategoryId")]
        [InverseProperty("AdTemplateConfigs")]
        public virtual ClassifiedAdsCategory ClassifiedAdsCategory { get; set; }
        [ForeignKey("FieldTypeId")]
        [InverseProperty("AdTemplateConfigs")]
        public virtual FieldType FieldType { get; set; }
        [InverseProperty("AdTemplateConfig")]
        public virtual ICollection<AdContent> AdContents { get; set; }
        public virtual ICollection<AdTemplateOption>? AdTemplateOptions { get; set; }

        public bool IsList { get; set; }
    }
}