// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vision.Models
{
    [Table("ClassifiedAdsCategory")]
    [Index("ClassifiedAdsCategoryParentId", Name = "IX_ClassifiedAdsCategory_ClassifiedAdsCategoryParentId")]
    public partial class ClassifiedAdsCategory
    {
        public ClassifiedAdsCategory()
        {
            AdTemplateConfigs = new HashSet<AdTemplateConfig>();
            ClassifiedAds = new HashSet<ClassifiedAd>();
            InverseClassifiedAdsCategoryParent = new HashSet<ClassifiedAdsCategory>();
        }

        [Key]
        public int ClassifiedAdsCategoryId { get; set; }
        [StringLength(50)]
        //[Required(ErrorMessage ="Required")]
        public string ClassifiedAdsCategoryTitleAr { get; set; }
        [StringLength(50)]
        //[Required(ErrorMessage = "Required")]
        public string ClassifiedAdsCategoryTitleEn { get; set; }
        public int? ClassifiedAdsCategorySortOrder { get; set; }
        //[StringLength(50)]
        public string ClassifiedAdsCategoryPic { get; set; }
        public bool ClassifiedAdsCategoryIsActive { get; set; }
        [StringLength(50)]
        public string ClassifiedAdsCategoryDescAr { get; set; }
        [StringLength(50)]
        public string ClassifiedAdsCategoryDescEn { get; set; }
        public int? ClassifiedAdsCategoryParentId { get; set; }

        [ForeignKey("ClassifiedAdsCategoryParentId")]
        [InverseProperty("InverseClassifiedAdsCategoryParent")]
        public virtual ClassifiedAdsCategory ClassifiedAdsCategoryParent { get; set; }
        [InverseProperty("ClassifiedAdsCategory")]
        public virtual ICollection<AdTemplateConfig> AdTemplateConfigs { get; set; }
        [InverseProperty("ClassifiedAdsCategoryParent")]
        public virtual ICollection<ClassifiedAdsCategory> InverseClassifiedAdsCategoryParent { get; set; }
        public virtual ICollection<ClassifiedAd> ClassifiedAds { get; set; }
    }
}