// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Vision.Models
{
    public partial class ClassifiedAd
    {
        public ClassifiedAd()
        {
            AdContents = new HashSet<AdContent>();
        }

        public long ClassifiedAdId { get; set; }
        public string TitleAr { get; set; }
        public string TitleEn { get; set; }
        public double Price { get; set; }
        public string MainPic { get; set; }
        public string Reel { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public DateTime? PublishDate { get; set; }
        //[Column(TypeName = "NVARCHAR")]
        //[StringLength(450)]
        
        public string UseId { get; set; }
        public string PhoneNumber { get; set; } = string.Empty;
        public int? Views { get; set; }
        public bool IsActive { get; set; }
        public int? CityId { get; set; }
        public int? AreaId { get; set; }
        public int? ClassifiedAdsCategoryId { get; set; }

        public virtual ClassifiedAdsCategory ClassifiedAdsCategory { get; set; }
        public virtual ICollection<AdContent> AdContents { get; set; }
        public virtual ICollection<Quotation> Quotations { get; set; }
        public virtual ICollection<AdsImage> AdsImages { get; set; }
    }
}